#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 13 15:53:23 EST 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim hostif_test_tb_behav -key {Behavioral:sim_1:Functional:hostif_test_tb} -tclbatch hostif_test_tb.tcl -view /drive/sda2/home/rameyn1/Physics-Gpu-2025/Nick/host_interface/hostif_test_tb_behav.wcfg -log simulate.log"
xsim hostif_test_tb_behav -key {Behavioral:sim_1:Functional:hostif_test_tb} -tclbatch hostif_test_tb.tcl -view /drive/sda2/home/rameyn1/Physics-Gpu-2025/Nick/host_interface/hostif_test_tb_behav.wcfg -log simulate.log

