# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Senior_proj/Nexys-Video-Master.xdc

# IP: /home/landaud1/other/Senior_proj/Physics-Gpu-2025/Francis/sp_gram_test_2/project_2/project_2.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/v_tc_0/v_tc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==v_tc_0 || ORIG_REF_NAME==v_tc_0} -quiet] -quiet

# IP: ip/pe_ram/pe_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pe_ram || ORIG_REF_NAME==pe_ram} -quiet] -quiet

# IP: ip/float_to_fixed/float_to_fixed.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==float_to_fixed || ORIG_REF_NAME==float_to_fixed} -quiet] -quiet

# IP: ip/fp_add/fp_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: ip/fp_sqrt/fp_sqrt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_sqrt || ORIG_REF_NAME==fp_sqrt} -quiet] -quiet

# IP: ip/fp_reciprocal/fp_reciprocal.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_reciprocal || ORIG_REF_NAME==fp_reciprocal} -quiet] -quiet

# IP: ip/fp_multiply/fp_multiply.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_multiply || ORIG_REF_NAME==fp_multiply} -quiet] -quiet

# IP: ip/fp_sub/fp_sub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_sub || ORIG_REF_NAME==fp_sub} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
