# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/landaud1/other/Senior_proj/Physics-Gpu-2025/DJ/Physics-GPU-2025/Physics-GPU-2025.srcs/sources_1/ip/float_to_fixed/float_to_fixed.xci
# IP: The module: 'float_to_fixed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/landaud1/other/Senior_proj/Physics-Gpu-2025/DJ/Physics-GPU-2025/Physics-GPU-2025.gen/sources_1/ip/float_to_fixed/float_to_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_fixed'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/landaud1/other/Senior_proj/Physics-Gpu-2025/DJ/Physics-GPU-2025/Physics-GPU-2025.srcs/sources_1/ip/float_to_fixed/float_to_fixed.xci
# IP: The module: 'float_to_fixed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/landaud1/other/Senior_proj/Physics-Gpu-2025/DJ/Physics-GPU-2025/Physics-GPU-2025.gen/sources_1/ip/float_to_fixed/float_to_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_fixed'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
