# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /drive/sda2/home/aldridf1/Senior_Project_2024/Physics-Gpu-2025/Francis/sp_gram_test_2/project_1/project_1.srcs/sources_1/ip/v_tc_0/v_tc_0.xci
# IP: The module: 'v_tc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /drive/sda2/home/aldridf1/Senior_Project_2024/Physics-Gpu-2025/Francis/sp_gram_test_2/project_1/project_1.gen/sources_1/ip/v_tc_0/v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /drive/sda2/home/aldridf1/Senior_Project_2024/Physics-Gpu-2025/Francis/sp_gram_test_2/project_1/project_1.gen/sources_1/ip/v_tc_0/v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /drive/sda2/home/aldridf1/Senior_Project_2024/Physics-Gpu-2025/Francis/sp_gram_test_2/project_1/project_1.srcs/sources_1/ip/v_tc_0/v_tc_0.xci
# IP: The module: 'v_tc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /drive/sda2/home/aldridf1/Senior_Project_2024/Physics-Gpu-2025/Francis/sp_gram_test_2/project_1/project_1.gen/sources_1/ip/v_tc_0/v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /drive/sda2/home/aldridf1/Senior_Project_2024/Physics-Gpu-2025/Francis/sp_gram_test_2/project_1/project_1.gen/sources_1/ip/v_tc_0/v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
