#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Nov 09 18:14:28 EST 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_phys_calc_behav -key {Behavioral:sim_1:Functional:tb_phys_calc} -tclbatch tb_phys_calc.tcl -view /home/landaud1/other/Senior_proj/Physics-Gpu-2025/DJ/Physics-GPU-2025/tb_phys_calc_behav.wcfg -log simulate.log"
xsim tb_phys_calc_behav -key {Behavioral:sim_1:Functional:tb_phys_calc} -tclbatch tb_phys_calc.tcl -view /home/landaud1/other/Senior_proj/Physics-Gpu-2025/DJ/Physics-GPU-2025/tb_phys_calc_behav.wcfg -log simulate.log

